/** Live site — used for QR codes, sharing, and fallbacks */
export const LIVE_URL = 'https://rahgir-beige.vercel.app';

export const SITE_URL = LIVE_URL;

export const SITE_HOST = 'rahgir-beige.vercel.app';

export const GITHUB_USER = 'https://github.com/Adi51244';
export const GITHUB_REPO = 'https://github.com/Adi51244/Rahgir';
export const SITE_OWNER = 'Aditya Kumar';

export const CULTURES = {
  punjabi: {
    id: 'punjabi',
    label: 'पंजाबी',
    labelEn: 'Punjabi',
    route: 'अमृतसर – चंडीगढ़ – दिल्ली',
    boarding: 'पंजाबी राहगीर प्लेलिस्ट',
    service: 'सरहद सेवा',
    quoteLeft: 'सरहद से · अमृतसर',
    quoteRight: 'दिल्ली तक',
    emoji: '🌾',
    playlistId: 'PLKGdFvuCgQRQ',
    dataFile: '/data/punjabi_default.json',
    ytMusic: 'https://music.youtube.com/playlist?list=PLKGdFvuCgQRQ',
    moods: [
      { id: 'default', label: '🌾 ऑल-टाइम हिट्स', file: '/data/punjabi_default.json', ytMusic: 'https://music.youtube.com/playlist?list=PLKGdFvuCgQRQ' },
      { id: 'love', label: '❤️ Love', file: '/data/punjabi_love.json', ytMusic: 'https://music.youtube.com/playlist?list=PLWr5TJ2aWQv8' },
      { id: 'sad', label: '💔 Sad', file: '/data/punjabi_sad.json', ytMusic: 'https://music.youtube.com/playlist?list=PLSq1fUwcUH-Q' },
    ],
    webImages: [
      '/Asset/Punjab/Web/punjab-roadway-scenery-1.webp',
      '/Asset/Punjab/Web/punjab-roadway-scenery-2.webp',
      '/Asset/Punjab/Web/punjab-roadway-scenery-3.webp',
      '/Asset/Punjab/Web/punjab_sunrise_golden_hour.webp',
      '/Asset/Punjab/Web/punjab_sunrise_dawn.webp',
      '/Asset/Punjab/Web/punjabi_night_highway.webp',
      '/Asset/Punjab/Web/punjabi_night_scene.webp',
      '/Asset/Punjab/Web/punjab_bus_night.webp',
      '/Asset/Punjab/Web/punjab_bus_headlights.webp',
      '/Asset/Punjab/Web/monsoon_rainy_punjab_roadway.webp',
      '/Asset/Punjab/Web/monsoon_rainy_punjab_scene.webp',
      '/Asset/Punjab/Web/misty_dawn_bus_2.webp',
      '/Asset/Punjab/Web/golden_hour_sunrise_2.webp',
      '/Asset/Punjab/Web/foggy_winter_night.webp',
      '/Asset/Punjab/Web/cold_foggy_winter_night.webp',
      '/Asset/Punjab/Web/bus_warm_glow.webp',
    ],
    mobileImages: [
      '/Asset/Punjab/Mobile/punjab_sunrise_portrait.webp',
      '/Asset/Punjab/Mobile/punjab_sunrise_reflection.webp',
      '/Asset/Punjab/Mobile/punjabi_night_bus.webp',
      '/Asset/Punjab/Mobile/punjab_night_highway.webp',
      '/Asset/Punjab/Mobile/punjab_roadways_night.webp',
      '/Asset/Punjab/Mobile/punjab_roadways_reflection.webp',
      '/Asset/Punjab/Mobile/misty_dawn_bus_6.webp',
      '/Asset/Punjab/Mobile/winter_dawn_snowy_bus.webp',
      '/Asset/Punjab/Mobile/foggy_dawn_bus.webp',
      '/Asset/Punjab/Mobile/moody_evening_reflection.webp',
      '/Asset/Punjab/Mobile/golden_hour_sunrise_4.webp',
    ],
  },
  hindi: {
    id: 'hindi',
    label: 'हिंदी',
    labelEn: 'Hindi',
    route: 'दिल्ली – आगरा – जयपुर',
    boarding: 'हिंदी राहगीर प्लेलिस्ट',
    service: 'राजधानी सेवा',
    quoteLeft: 'दिलवालों की · दिल्ली से',
    quoteRight: 'रात भर सफर',
    emoji: '📻',
    playlistId: 'PLeFezh2862uI',
    dataFile: '/data/hindi_love.json',
    ytMusic: 'https://music.youtube.com/playlist?list=PLeFezh2862uI',
    moods: [
      { id: 'love', label: '❤️ Love', file: '/data/hindi_love.json', ytMusic: 'https://music.youtube.com/playlist?list=PLeFezh2862uI' },
      { id: 'old', label: '📻 Old Classics', file: '/data/hindi_old.json', ytMusic: 'https://music.youtube.com/playlist?list=PLWxEliA7bRZY' },
      { id: 'party', label: '🎉 Party', file: '/data/hindi_party.json', ytMusic: 'https://music.youtube.com/playlist?list=PLdEp4C6yCxW0' },
    ],
    webImages: [
      '/Asset/Hindi/web/Delhi_Variation.webp',
      '/Asset/Hindi/web/Delhi_Variation 2.webp',
      '/Asset/Hindi/web/Delhi_Variation 3.webp',
      '/Asset/Hindi/web/Delhi_Variation 4.webp',
      '/Asset/Hindi/web/Delhi_Variation 5.webp',
      '/Asset/Hindi/web/connaught_place_dawn.webp',
      '/Asset/Hindi/web/connaught_place_night.webp',
      '/Asset/Hindi/web/delhi_golden_sunset.webp',
      '/Asset/Hindi/web/delhi_night_bus.webp',
      '/Asset/Hindi/web/delhi_night_milky_way.webp',
      '/Asset/Hindi/web/delhi_night_milky_way_1.webp',
      '/Asset/Hindi/web/delhi_night_milkyway.webp',
      '/Asset/Hindi/web/delhi_sunset_epic.webp',
      '/Asset/Hindi/web/delhi_sunset_golden_hour.webp',
      '/Asset/Hindi/web/foggy_dawn_bus_2.webp',
      '/Asset/Hindi/web/foggy_dawn_bus_3.webp',
      '/Asset/Hindi/web/foggy_dawn_bus_4.webp',
      '/Asset/Hindi/web/golden_hour_delhi.webp',
      '/Asset/Hindi/web/golden_hour_delhi_sunset.webp',
      '/Asset/Hindi/web/golden_hour_sunset_1.webp',
      '/Asset/Hindi/web/misty_dawn_bus_9.webp',
      '/Asset/Hindi/web/misty_dawn_bus_10.webp',
      '/Asset/Hindi/web/misty_dawn_bus_11.webp',
      '/Asset/Hindi/web/misty_dawn_cityscape.webp',
      '/Asset/Hindi/web/misty_dawn_delhi.webp',
    ],
    mobileImages: [
      '/Asset/Hindi/Mobile/delhi_bus_diwali_night_1.webp',
      '/Asset/Hindi/Mobile/delhi_bus_golden_sunset.webp',
      '/Asset/Hindi/Mobile/delhi_diwali_night.webp',
      '/Asset/Hindi/Mobile/delhi_diwali_night_1.webp',
      '/Asset/Hindi/Mobile/delhi_diwali_night_2.webp',
      '/Asset/Hindi/Mobile/delhi_foggy_dawn.webp',
      '/Asset/Hindi/Mobile/delhi_golden_sunset_1.webp',
      '/Asset/Hindi/Mobile/delhi_milky_way_night.webp',
      '/Asset/Hindi/Mobile/delhi_night_bus_1.webp',
      '/Asset/Hindi/Mobile/delhi_night_golden.webp',
      '/Asset/Hindi/Mobile/delhi_night_milky_way_2.webp',
      '/Asset/Hindi/Mobile/delhi_night_milky_way_4.webp',
      '/Asset/Hindi/Mobile/delhi_night_milky_way_5.webp',
      '/Asset/Hindi/Mobile/delhi_night_milky_way_6.webp',
      '/Asset/Hindi/Mobile/delhi_night_milky_way_7.webp',
      '/Asset/Hindi/Mobile/delhi_sunset_bus.webp',
      '/Asset/Hindi/Mobile/delhi_sunset_bus_1.webp',
      '/Asset/Hindi/Mobile/delhi_sunset_portrait.webp',
      '/Asset/Hindi/Mobile/delhi_sunset_street.webp',
      '/Asset/Hindi/Mobile/foggy_delhi_night_3.webp',
      '/Asset/Hindi/Mobile/foggy_delhi_night_4.webp',
      '/Asset/Hindi/Mobile/nighttime_delhi_street.webp',
    ],
  },
  haryanvi: {
    id: 'haryanvi',
    label: 'हरियाणवी',
    labelEn: 'Haryanvi',
    route: 'रोहतक – गुरुग्राम – हिसार',
    boarding: 'हरियाणवी राहगीर प्लेलिस्ट',
    service: 'देसी सेवा',
    quoteLeft: 'देसी ठाठ · रोहतक से',
    quoteRight: 'हिसार तक',
    emoji: '🚜',
    playlistId: 'PLIhTnCYdopOY',
    dataFile: '/data/haryanvi_party.json',
    ytMusic: 'https://music.youtube.com/playlist?list=PLIhTnCYdopOY',
    moods: [
      { id: 'party', label: '🎉 Party', file: '/data/haryanvi_party.json', ytMusic: 'https://music.youtube.com/playlist?list=PLIhTnCYdopOY' },
      { id: 'love', label: '❤️ Love', file: '/data/haryanvi_love.json', ytMusic: 'https://music.youtube.com/playlist?list=PLe1YDFEDHOe0' },
    ],
    webImages: [
      '/Asset/Haryana/Web/Haryana_Variation 1.webp',
      '/Asset/Haryana/Web/Haryana_Variation 2.webp',
      '/Asset/Haryana/Web/Haryana_Variation 3.webp',
      '/Asset/Haryana/Web/Haryana_Variation 4.webp',
      '/Asset/Haryana/Web/Haryana_Variation 5.webp',
      '/Asset/Haryana/Web/Haryana_Variation 6.webp',
      '/Asset/Haryana/Web/blue_hour_bus_reflection.webp',
      '/Asset/Haryana/Web/cinematic_golden_hour.webp',
      '/Asset/Haryana/Web/cinematic_golden_sunset.webp',
      '/Asset/Haryana/Web/golden_hour_sunset_2.webp',
      '/Asset/Haryana/Web/haryanvi_night_scene.webp',
      '/Asset/Haryana/Web/misty_dawn_bus_12.webp',
      '/Asset/Haryana/Web/misty_dawn_bus_13.webp',
      '/Asset/Haryana/Web/night_milky_way_scene.webp',
      '/Asset/Haryana/Web/nighttime_rural_scene.webp',
      '/Asset/Haryana/Web/rainy_bus_reflection.webp',
      '/Asset/Haryana/Web/rainy_evening_reflections.webp',
      '/Asset/Haryana/Web/to_misty_dawn_bus.webp',
    ],
    mobileImages: [
      '/Asset/Haryana/Mobile/diwali_dhaba_evening.webp',
      '/Asset/Haryana/Mobile/diwali_festival_sunset.webp',
      '/Asset/Haryana/Mobile/diwali_night_scene.webp',
      '/Asset/Haryana/Mobile/diwali_night_scene_1.webp',
      '/Asset/Haryana/Mobile/foggy_night_bus.webp',
      '/Asset/Haryana/Mobile/foggy_night_bus_1.webp',
      '/Asset/Haryana/Mobile/foggy_winter_night_4.webp',
      '/Asset/Haryana/Mobile/golden_hour_bus.webp',
      '/Asset/Haryana/Mobile/haryana_night_scene.webp',
      '/Asset/Haryana/Mobile/haryana_night_sky.webp',
      '/Asset/Haryana/Mobile/haryana_sunset_scene.webp',
      '/Asset/Haryana/Mobile/nighttime_dhaba_scene_1.webp',
      '/Asset/Haryana/Mobile/rural_sunset_portrait.webp',
      '/Asset/Haryana/Mobile/warm_night_street.webp',
    ],
  },
  bhojpuri: {
    id: 'bhojpuri',
    label: 'भोजपुरी',
    labelEn: 'Bhojpuri',
    route: 'पटना – वाराणसी – गंगा घाट',
    boarding: 'भोजपुरी राहगीर प्लेलिस्ट',
    service: 'गंगा सेवा',
    quoteLeft: 'गंगा घाट · पटना से',
    quoteRight: 'काशी तक',
    emoji: '🪔',
    playlistId: 'PLVTwrTzYCvPU',
    dataFile: '/data/bhojpuri_default.json',
    ytMusic: 'https://music.youtube.com/playlist?list=PLVTwrTzYCvPU',
    moods: [
      { id: 'default', label: '🪔 गंगा सेवा हिट्स', file: '/data/bhojpuri_default.json', ytMusic: 'https://music.youtube.com/playlist?list=PLVTwrTzYCvPU' },
      { id: 'chhath', label: '🪔 छठ Special', file: '/data/bhojpuri_chhath.json', ytMusic: 'https://music.youtube.com/playlist?list=PLfvI9MdTikug' },
    ],
    webImages: [
      '/Asset/Bihar/Web/bihar-roadway-scenery-1.webp',
      '/Asset/Bihar/Web/bihar-roadway-scenery-2.webp',
      '/Asset/Bihar/Web/bihar-roadway-scenery-3.webp',
      '/Asset/Bihar/Web/misty_golden_sunrise.webp',
      '/Asset/Bihar/Web/misty_dawn_blue_hour.webp',
      '/Asset/Bihar/Web/nighttime_bihar_highway.webp',
      '/Asset/Bihar/Web/nighttime_river_scene.webp',
      '/Asset/Bihar/Web/monsoon_rainy_evening.webp',
      '/Asset/Bihar/Web/monsoon_night_rain.webp',
      '/Asset/Bihar/Web/golden_hour_sunrise_1.webp',
    ],
    mobileImages: [
      '/Asset/Bihar/Mobile/bihar_sunrise_reflection.webp',
      '/Asset/Bihar/Mobile/misty_dawn_ganga.webp',
      '/Asset/Bihar/Mobile/starry_night_ganga_scene.webp',
      '/Asset/Bihar/Mobile/rainy_evening_ghat_reflection.webp',
      '/Asset/Bihar/Mobile/golden_hour_reflection.webp',
      '/Asset/Bihar/Mobile/misty_dawn_highway.webp',
      '/Asset/Bihar/Mobile/starry_night_bus_scene.webp',
      '/Asset/Bihar/Mobile/rainy_evening_bus.webp',
    ],
  },
  nepali: {
    id: 'nepali',
    label: 'नेपाली',
    labelEn: 'Nepali',
    route: 'काठमाण्डौ – पोखरा – बागलुङ',
    boarding: 'नेपाली राहगीर प्लेलिस्ट',
    service: 'हिमालय सेवा',
    altitude: '१,४०० m',
    altitudeLabel: 'औसत ऊँचाई',
    quoteLeft: 'रात भर · हिमालय से',
    quoteRight: 'पोखरा तक',
    emoji: '🇳🇵',
    playlistId: 'PLETcP_FdLOGY',
    dataFile: '/data/nepali_default.json',
    ytMusic: 'https://music.youtube.com/playlist?list=PLETcP_FdLOGY',
    moods: [
      { id: 'default', label: '🏔️ हिमालयन धुन', file: '/data/nepali_default.json', ytMusic: 'https://music.youtube.com/playlist?list=PLETcP_FdLOGY' },
    ],
    webImages: [
      '/Asset/Nepal/Web/nepal-roadway-scenery-5.webp',
      '/Asset/Nepal/Web/nepal-roadway-scenery-1.webp',
      '/Asset/Nepal/Web/nepal-roadway-scenery-2.webp',
      '/Asset/Nepal/Web/nepal-roadway-scenery-3.webp',
      '/Asset/Nepal/Web/nepal-roadway-scenery-4.webp',
      '/Asset/Nepal/Web/golden_himalayan_sunrise_1.webp',
      '/Asset/Nepal/Web/golden_hour_sunrise.webp',
      '/Asset/Nepal/Web/golden_hour_sunset.webp',
      '/Asset/Nepal/Web/himalayan_night_milky_way.webp',
      '/Asset/Nepal/Web/himalayan_night_scene.webp',
      '/Asset/Nepal/Web/himalayan_sunrise_golden_hour.webp',
      '/Asset/Nepal/Web/misty_dawn_bus.webp',
      '/Asset/Nepal/Web/misty_dawn_nepal_bus.webp',
      '/Asset/Nepal/Web/monsoon_evening_rain.webp',
      '/Asset/Nepal/Web/nepal_monsoon_bus.webp',
      '/Asset/Nepal/Web/nepal_night_bus.webp',
      '/Asset/Nepal/Web/nepal_night_scene.webp',
      '/Asset/Nepal/Web/rainy_night_reflections.webp',
      '/Asset/Nepal/Web/foggy_dawn_bus_1.webp',
      '/Asset/Nepal/Web/volumetric_headlight_mist.webp',
    ],
    mobileImages: [
      '/Asset/Nepal/Mobile/nepal_bus_golden_sunrise.webp',
      '/Asset/Nepal/Mobile/himalayan_sunrise_portrait.webp',
      '/Asset/Nepal/Mobile/himalayan_sunset_portrait.webp',
      '/Asset/Nepal/Mobile/golden_himalayan_sunrise.webp',
      '/Asset/Nepal/Mobile/moonlit_himalayan_bus.webp',
      '/Asset/Nepal/Mobile/nepal_night_milky_way.webp',
      '/Asset/Nepal/Mobile/monsoon_night_bus.webp',
      '/Asset/Nepal/Mobile/monsoon_rainy_reflection.webp',
      '/Asset/Nepal/Mobile/misty_dawn_bus_3.webp',
      '/Asset/Nepal/Mobile/nepal_night_bus_1.webp',
      '/Asset/Nepal/Mobile/nepal_night_bus_2.webp',
      '/Asset/Nepal/Mobile/foggy_winter_night_1.webp',
      '/Asset/Nepal/Mobile/nepal_bus_winter_night.webp',
    ],
  },
};

export const HORN_SOUNDS = [
  '/Asset/Horn Sound/Bus Horn.mp3',
  '/Asset/Horn Sound/Kerala Bus Horn Download Mp3.mp3',
  '/Asset/Horn Sound/Rajasthani Bus Horn Download.mp3',
  '/Asset/Horn Sound/Private Bus Horn Download Tamil.mp3',
  '/Asset/Horn Sound/Lorry Horn Sound Mp3 Download.mp3',
  '/Asset/Horn Sound/Bus Horn Sound Download Tamil Nadu.mp3',
];

export const SLIDE_DURATION_MS = 15000;

export const DEFAULT_CULTURE = 'punjabi';

export const CULTURE_SIGNIFICANCE = {
  punjabi: {
    title: 'पंजाबी संस्कृति की महत्वता',
    body: 'पंजाब की NH सड़कें अमृतसर से दिल्ली तक — सरसों के खेत, ढाबे, और ट्रक आर्ट वाली बसें। पंजाबी गाने की ताल, भंगड़े की लय, और दिल्ली-अमृतसर हाइवे की रात — यह सब एक साथ मिलकर सफ़र को उत्सव बना देते हैं।',
    extra: 'पंजाब में हर ढाबे पर म्यूज़िक, हर बस में भंगड़ा — यह सिर्फ़ संगीत नहीं, जीवनशैली है। NH-1 और NH-48 की रातें, ट्रक ड्राइवरों के रेडियो, और यात्रियों का साथ — सब कुछ पंजाबी धुन में बदल जाता है।',
    highlights: ['अमृतसर – चंडीगढ़ – दिल्ली रूट', 'ढाबे और सरसों के खेत', 'भंगड़ा बीट्स, लव और सैड मेलोडी', 'NH हाइवे की रात भर यात्रा'],
    songs: 'इस प्लेलिस्ट में पंजाबी पॉप, भंगड़ा बीट्स, रोमांटिक लव ट्रैक्स और हाइवे पर सुनने वाले क्लासिक ट्रैक हैं।',
    journey: 'अमृतसर की सुनहरी गुरुद्वारे की रोशनी से दिल्ली की भीड़ तक — पंजाबी संगीत हर किलोमीटर पर ऊर्जा भर देता है।',
  },
  hindi: {
    title: 'हिंदी / दिल्ली संस्कृति की महत्वता',
    body: 'दिलवालों की दिल्ली से आगरा और जयपुर तक — पुरानी दिल्ली की गलियाँ, कनाट प्लेस की रातें, और नेशनल हाइवे की रोशनी। 90s के सदाबहार नगमे, रोमांटिक धुनें और लेट नाइट पार्टी ट्रैक्स इस सफर की आत्मा हैं।',
    extra: 'दिल्ली की नाइट लाइफ, इंडिया गेट की शामें और हाइवे पर गूँजते बॉलीवुड क्लासिक्स हर मुसाफिर को अपनी धुन में बांध लेते हैं।',
    highlights: ['दिल्ली – आगरा – जयपुर एक्सप्रेसवे', 'सदाबहार ओल्ड क्लासिक्स & 90s Hits', 'रोमांटिक लव ट्रैक्स & नाइट पार्टी', 'राजधानी बस का अविस्मरणीय सफर'],
    songs: 'इस प्लेलिस्ट में बॉलीवुड के ऑल-टाइम लव गाने, नॉस्टैल्जिक ओल्ड क्लासिक्स और एनर्जेटिक पार्टी हिट्स हैं।',
    journey: 'कनाट प्लेस की जगमगाहट से ताज के शहर आगरा तक — हर मोड़ पर एक नई सदाबहार धुन।',
  },
  haryanvi: {
    title: 'हरियाणवी संस्कृति की महत्वता',
    body: 'हरियाणा के देसी ठाठ, रोहतक से हिसार और गुरुग्राम — चौपालों की रागिनी, खेतों की ताज़गी और हाई-बास देसी बीट्स। हरियाणवी गाने सफर में एक अलग ही जोश और ऊर्जा भर देते हैं।',
    extra: 'देसी बोली, दमदार बीट्स और डीजे-पार्टी की रौनक — हरियाणवी म्यूजिक हर उम्र के मुसाफिरों को थिरकने पर मजबूर कर देता है।',
    highlights: ['रोहतक – गुरुग्राम – हिसार रूट', 'देसी रागिनी और हाई-बास पार्टी बीट्स', 'हरियाणवी लव और लोक संगीत', 'खेतों और ढाबों का देसी माहौल'],
    songs: 'इस प्लेलिस्ट में टॉप हरियाणवी पार्टी डांस हिट्स और मीठे लव ट्रैक्स का बेहतरीन कॉम्बिनेशन है।',
    journey: 'रोहतक की चौपाल से गुरुग्राम की साइबर सिटी तक — देसी अंदाज में रात का सफर।',
  },
  bhojpuri: {
    title: 'भोजपुरी संस्कृति की महत्वता',
    body: 'गंगा के घाट, पटना से वाराणसी — भोजपुरी संस्कृति की धड़कन यहाँ बसती है। होली, छठ, और गंगा आरती की परंपरा इन सड़कों पर जीवंत है। भोजपुरी गाने — लोक, फिल्मी, और नए रिमिक्स — गंगा की लहरों जैसे बहते हैं।',
    extra: 'भोजपुरी गीतों में गंगा, खेत, और गाँव की मिट्टी की खुशबू है। छठ पूजा की शाम, होली की रंगीन सुबह, और गंगा आरती की दीयों की रोशनी — ये सब भोजपुरी संगीत में जीवंत हैं।',
    highlights: ['पटना – वाराणसी – गंगा घाट', 'छठ पूजा की पावन धुन', 'भोजपुरी लोकगीत और फिल्मी हिट', 'गंगा किनारे की रात भर सफर'],
    songs: 'इस प्लेलिस्ट में भोजपुरी लोकगीत, छठ महापर्व के पावन गीत और गंगा घाट की रात के लिए बने ट्रैक हैं।',
    journey: 'पटना की राजधानी से वाराणसी के पवित्र घाट तक — गंगा के किनारे हर मोड़ पर भोजपुरी की आवाज़ गूँजती है।',
  },
  nepali: {
    title: 'नेपाली संस्कृति की महत्वता',
    body: 'नेपाल की सड़कें, विशेषकर काठमाण्डौ से पोखरा और बागलुङ तक, हज़ारों यात्रियों को हिमालय की गोद में ले जाती हैं। यहाँ के गाने — लोक, आधुनिक रक, और यात्रा की धुन — बस की खिड़की से दिखते बादल, झरने और चियाँ बाज़ार की ज़िंदगी को जीवंत कर देते हैं।',
    extra: 'नेपाली संगीत में दोहोरी, लोकगीत, और ट्रक-बस कल्चर की अनूठी मिली-जुली परंपरा है। पहाड़ी रास्तों पर हर मोड़ पर एक नई धुन, एक नई कहानी मिलती है — और वही राहगीर की आत्मा है।',
    highlights: ['हिमालय की रात भर की बस यात्रा', 'पोखरा की झील और पर्वत धुन', 'नेपाली लोकगीत और आधुनिक रक', 'दोहोरी और यात्रा गीत'],
    songs: 'इस प्लेलिस्ट में नेपाली यात्रा गाने, पहाड़ी धुनें और रात भर सुनने लायक ट्रैक हैं।',
    journey: 'काठमाण्डौ की भीड़भाड़ वाली सड़क से शुरू होकर, पोखरा की शांत झील तक — यह सफ़र सिर्फ़ दूरी नहीं, बल्कि संस्कृति, भाषा और संगीत का सफ़र है।',
  },
};
